controllers/book.py
from actions.booking.booking import BookingActions
from flask import Blueprint, session, render_template, request, flash, redirect, url_for
from actions.bus.bus import BusActions
from util.date_utils import get_day_name

booking = Blueprint('book', __name__)


@booking.route('/search', methods=['GET'])
def search_bus():
    if not session.get("user"):
        return redirect(url_for('login'))
    else:
        if request.method == 'GET':
            start = request.args.get('from')
            destination = request.args.get('to')
            date = request.args.get('date')
            session['date'] = date
            day = get_day_name(session['date'])
            bus_list = BookingActions().get_user_request_buses(
                search={'from': start, 'to': destination, 'date': date})
            return render_template('user-request-buses.html', buses=bus_list, day=day, user=session.get("user"))


@booking.route('/book/<schedule_id>')
def seat_book(schedule_id):
    if not session.get("user"):
        return redirect(url_for('login'))
    else:
        _schedule = BusActions().get_bus_schedule(schedule_id)
        _bus = BusActions().get_bus(_schedule['bus_number'])
        return render_template('seat-booking.html', schedule=_schedule, bus=_bus, book_date=session['date'], user=session.get("user"))


@booking.route('/confirm-booking', methods=['POST'])
def confirm_booking():
    if not session.get("user"):
        return redirect(url_for('login'))
    else:
        if request.method == 'POST':
            user_id = session['user']
            bus_number = int(request.form['bus_id'])
            schedule_id = request.form['schedule_id']
            window_left = request.form.getlist('window_left_seats')
            window_right = request.form.getlist('window_right_seats')
            left = request.form.getlist('left_seats')
            right = request.form.getlist('right_seats')
            price = request.form['price']
            book_date = session['date']
            record = {'user_id': user_id, 'bus_number': bus_number, 'schedule_id': schedule_id, 'window_left': window_left,
                      'window_right': window_right, 'left': left, 'right': right, 'booked_date': book_date, 'booking_price': price}
            booking = BookingActions().book_ticket(record)
            session.pop('book_date', None)
            return render_template('booking-done.html', bus=BusActions().get_bus(bus_number), booking=booking, user=session.get("user"))


@booking.route('/bookings')
def booking_list():
    if not session.get("user"):
        return redirect(url_for('login'))
    bookings = BookingActions().get_bookings(session['user'])
    return render_template('bookings-list.html', bookinglist=bookings, user=session.get("user"))


@booking.route('/cancel')
def cancel_booking():
    if not session.get("user"):
        return redirect(url_for('login'))
    else:
        _user_id = session['user']
        _booking_id = request.args.get('booking_id')
        if _booking_id:
            BookingActions().booking_cancellation(booking_id=_booking_id, booked_by=_user_id)
            flash('Booking cancelled successfully', 'alert-danger')
            return redirect(url_for('book.booking_list', user_id=_user_id))

controllers/bus.py
from flask import Blueprint, jsonify
from actions.bus.bus import BusActions


bus = Blueprint('bus', __name__)


@bus.route('/bus/<int:bus_no>', methods=['GET'])
def get_bus(bus_no):
    bus = BusActions().get_bus(bus_no)
    return jsonify(bus) if bus else (jsonify({'message': 'No bus found'}), 404)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bus.css') }}" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@200&display=swap" rel="stylesheet" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://kit.fontawesome.com/8d1ad05b63.js" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
 


  <title>{% block title %} {% endblock %}</title>
</head>

<body>

  {% with messages = get_flashed_messages(with_categories = True) %}
  {% if messages %}
  {% for category, message in messages %}
  <div class="container px-5 mt-3">
    <div class="alert {{category}} alert-dismissible">
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      <strong>{{message}}</strong>
    </div>
  </div>
  <br>
  {% endfor %}
  {% endif %}
  {% endwith %}

  {% block content %} {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

templates/booking-done.html
{% extends 'base.html' %} {% block title %} Booking Success {% endblock %}
{% include 'navbar.html' %}
{% block content %}

<div class="container mt-3">
  <div class="receipt">
    <h2 class="text-center">Booking Confirmed !</h2>
    <p>Bus Name: {{ bus.name }}</p>
    <p>Journey: {{ bus.start }} ➜ {{ bus.destination }}</p>
    <p>Journey Date: {{ booking.booked_date }}</p>
    <p>
      Seats booked: {% for i in booking.booked_tickets.window_left %} A{{i}} {%
      endfor %} {% for i in booking.booked_tickets.left %} B{{i}} {% endfor %}
      {% for i in booking.booked_tickets.right %} C{{i}} {% endfor %} {% for i
      in booking.booked_tickets.window_right %} D{{i}} {% endfor %}
    </p>

    <p>Total Price: {{ booking.booking_price }}</p>
    <br />
    <a href="{{url_for('index')}}" class="text-success text-decoration-none">Return to home</a>
  </div>
</div>

{% include 'footer.html' %} 

{% endblock %}

templates/bookings-list.html
{% extends 'base.html' %} {% block title %} Booking List {% endblock %} {%
include 'navbar.html' %} {% block content %}

<div class="content">
  {% if bookinglist %} {% for booking in bookinglist %}
  <div class="booking">
    <div class="image-cont">
      <img src={{url_for('static', filename='img/ticket.png' ) }} alt="bus image
      here" class="bus-image">
    </div>
    <div class="booking_list_data_wrapper">
      <div class="booking-content">
        <div class="booking-id">
          <span class="fw-bold">Booking ID:</span><span>{{booking._id}}</span>
        </div>
        <div class="booking-date" id="bookingdatediv">
          <span class="fw-bold">Booking Date:</span>
          <span id="bookingdate-{{booking._id}}">{{booking.booked_date}}</span>
        </div>
        <div class="booking-price">
          <span class="fw-bold">Booking Price:</span> {{booking.booking_price}}
        </div>
        <div class="booked-bus-id">
          <span class="fw-bold">Booked Bus Number:</span> {{booking.bus_number}}
        </div>
        <div class="booked-on">
          <span class="fw-bold">Booked On:</span>
          {{booking.booked_on.strftime('%d-%m-%Y %H:%M:%S')}}
        </div>
        <div class="booking-seats">
          <span class="fw-bold">Booked Seats:</span> {% for i in
          booking.booked_tickets.window_left %} A{{i}} {% endfor %} {% for i in
          booking.booked_tickets.left %} B{{i}} {% endfor %} {% for i in
          booking.booked_tickets.right %} C{{i}} {% endfor %} {% for i in
          booking.booked_tickets.window_right %} D{{i}} {% endfor %}

          <!-- <i class="fa-solid fa-trash fa-lg" id="cancel-{{booking._id}}" style="cursor: pointer" title="Delete"></i> -->
        </div>
      </div>
      <div class="cancel_book">
        <span id="dustbin-{{booking._id}}"> </span>
      </div>
    </div>
  </div>

  <script>
    function SelectiveCancellation() {
      var date = document.getElementById(
        "bookingdate-{{booking._id}}"
      ).innerHTML;
      var array = date.split("-");
      var a = parseInt(array[0]);
      var b = parseInt(array[1]);
      var c = parseInt(array[2]);
      var dateOne = new Date(a, b - 1, c);
      console.log(dateOne);
      var today = new Date();
      console.log(today);
      if (dateOne > today) {
        document.getElementById("dustbin-{{booking._id}}").innerHTML +=
          '<button class="cancel" id="cancel-{{booking._id}}" style="cursor: pointer" title="Cancel">Cancel</button>';
      }
    }

    SelectiveCancellation();

    function CancellationClick() {
      document.addEventListener("click", (e) => {
        if (e.target.id === "cancel-{{booking._id}}") {
          if (confirm("Are you sure you want to cancel this booking?")) {
            window.location.href =
              '{{ url_for("book.cancel_booking", booking_id=booking._id) }}';
          }
        }
      });
    }

    CancellationClick();
  </script>
  {% endfor %} {% else %}
  <h3 class="text-center">No bookings found</h3>
  {% endif %}
</div>
{% include 'footer.html' %} {% endblock %}

templates/index.html
{% extends 'base.html' %} {% block title %} Index {% endblock %}
{% include 'navbar.html' %}
{% block content %}

<div class="main_div">
  <form class="Main-input" action="{{url_for('book.search_bus')}}" method="get">
    <div class="form_elements">
      <li class="homePageForm">
        <p class="headings"><i class="fa-solid fa-house"></i> </p>
        <div class="dropdown">
          <input class="inputs" id="myInput" type="text" list="start_locations" name="from" placeholder="from"
            autocomplete="off" />
          <!-- <p id="datalist"></p> -->
        </div>
      </li>
      <li class="homePageForm">
        <p class="headings"><i class="fa-solid fa-location-dot"></i> </p>
        <p>
          <input class="inputs rogue" id="myInput2" list="destination_locations" type="text" name="to" placeholder="to"
            autocomplete="off" required />
        </p>
      </li>

      <li class="homePageForm">
        <p class="headings"><i class="fa-regular fa-calendar"></i> </p>
        <input id="input_date" class="inputs date" type="date" name="date" required />
      </li>
      <li class="homePageForm">
        <button class="button" type="submit"><i class="fa-sharp fa-solid fa-magnifying-glass search"></i></button>
      </li>
    </div>
  </form>
</div>


<div class="clearfix aa our-promise-blocks animated slideInLeft delay-1s" id="advantage">
  <div class="fl rest1 appear-first aa-33 animate" id="customer1">
    <div class="stats">
      <div class="imgCont rest1 animate">
        <img src="//s2.rdbuz.com/web/images/home/benefits.png" height="90">
      </div>
      <div class="tilleBlock rest1 animate">
        UNMATCHED BENEFITS
      </div>
      <div class="second-level-heading descCont rest1 animate">
        We take care of your travel beyond ticketing by providing you with innovative and unique benefits.
      </div>
    </div>
    <div>
      <img class="stats_img" src="static/img/log.jpg" alt="">
    </div>

  </div>
  <div class="fl rest1 animated loop slideInRight delay-2s" id="customer1">
    <div>
      <img class="stats_img" src="static/img/log3.jpg" alt="">
    </div>

    <div class="stats">
      <div class="imgCont rest1 animate">
        <img src="//s1.rdbuz.com/web/images/home/customer_care.png" height="90">
      </div>
      <div class="tilleBlock rest1 animate">
        SUPERIOR CUSTOMER SERVICE
      </div>
      <div class="second-level-heading descCont rest1 animate">
        We put our experience and relationships to good use and are available to solve your travel issues.
      </div>
    </div>

  </div>
  <div class="fl rest1 animated slideInLeft delay-3s" id="customer1">
    <div class="stats">
      <div class="imgCont rest1 animate">
        <img src="//s1.rdbuz.com/web/images/home/lowest_Fare.png" height="90">
      </div>
      <div class="tilleBlock rest1 animate">
        LOWEST PRICES
      </div>
      <div class="second-level-heading descCont rest1 animate">
        We always give you the lowest price with the best partner offers.
      </div>
    </div>
    <div>
      <img class="stats_img" src="static/img/log2.jpg" alt="image">
    </div>

  </div>
</div>


{% include 'footer.html' %} 

<script type="text/javascript">
  $(function () {
    var dtToday = new Date();

    var month = dtToday.getMonth() + 1;
    var day = dtToday.getDate();
    var year = dtToday.getFullYear();
    if (month < 10)
      month = '0' + month.toString();
    if (day < 10)
      day = '0' + day.toString();
    var maxDate = year + '-' + month + '-' + day;
    $('#input_date').attr('min', maxDate);
  });
</script>

<datalist id="start_locations">
  {% for i in start_locations %}
  <option value="{{i}}">{{i}}</option>
  {% endfor %}
</datalist>

<datalist id="destination_locations">
  {% for i in destination_locations %}
  <option value="{{i}}">{{i}}</option>
  {% endfor %}
</datalist>

{% endblock %}

templates/seat-booking.html
{% extends 'base.html' %} {% block title %} Seat Booking {% endblock %} {%
include 'navbar.html' %} {% block content %}

<div class="container d-flex">
  <form method="post" id="seats">
    <div class="shadow flex-fill" id="bus-outline">
      {% for i in range(1, schedule['seat_columns'] + 1) %}
      <div class="mb-1">
        {% if schedule['seats']['window_left']['seats'][i-1]['seat_occupied'] ==
        False %}
        <!-- Left Window Seat -->
        <label title="Available" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_unoccupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="window_left_seats"
            class="seat-checkbox window_seat"
            value="{{ i }}"
            onclick="calculate_price()"
          /><span style="font-size: 11px">A{{ i }}</span></label
        >
        {% else %}
        <label title="Booked" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_occupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="window_left_seats"
            class="seat-checkbox"
            value="{{ i }}"
            disabled
          /><span style="font-size: 11px">A{{ i }}</span></label
        >
        {% endif %} {% if
        schedule['seats']['left']['seats'][i-1]['seat_occupied'] == False %}
        <!-- Left Seat -->
        <label title="Available" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_unoccupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="left_seats"
            class="seat-checkbox normal_seat"
            value="{{ i }}"
            onclick="calculate_price()"
          /><span style="font-size: 11px">B{{ i }}</span></label
        >
        {% else %}
        <label title="Booked" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_occupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="left_seats"
            class="seat-checkbox"
            value="{{ i }}"
            disabled
          /><span style="font-size: 11px">B{{ i }}</span></label
        >
        {% endif %}

        <span style="padding-left: 2rem">&nbsp;</span>

        {% if schedule['seats']['right']['seats'][i-1]['seat_occupied'] == False
        %}
        <!-- Right Seat -->
        <label title="Available" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_unoccupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="right_seats"
            class="seat-checkbox normal_seat"
            value="{{ i }}"
            onclick="calculate_price()"
          /><span style="font-size: 11px">C{{ i }}</span></label
        >
        {% else %}
        <label title="Booked" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_occupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="right_seats"
            class="seat-checkbox"
            value="{{ i }}"
            disabled
          /><span style="font-size: 11px">C{{ i }}</span></label
        >
        {% endif %} {% if
        schedule['seats']['window_right']['seats'][i-1]['seat_occupied'] ==
        False %}
        <!-- Right Window Seat -->
        <label title="Available" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_unoccupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="window_right_seats"
            class="seat-checkbox window_seat"
            value="{{ i }}"
            onclick="calculate_price()"
          /><span style="font-size: 11px">D{{ i }}</span></label
        >
        {% else %}
        <label title="Booked" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_occupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="window_right_seats"
            class="seat-checkbox"
            value="{{ i }}"
            disabled
          /><span style="font-size: 11px">D{{ i }}</span></label
        >
        {% endif %}
      </div>
      {% endfor %}
    </div>
    <input type="hidden" name="price" id="price" />
    <input type="hidden" name="schedule_id" value="{{ schedule['_id'] }}" />
    <input type="hidden" name="bus_id" value="{{ schedule['bus_number'] }}" />
  </form>

  <div class="flex-fill">
    <div class="container mt-3 d-grid px-5">
      <div class="d-flex">
        <h1 class="flex-grow-1" id="bus-name">{{bus._id}} - {{bus.name}}</h1>
        <h4 class="pt-2" id="bus-date">{{ book_date }}</h4>
      </div>
      <p class="lead mt-2" id="bus-startfin">
        {{bus.start}} -> {{bus.destination}}
      </p>
      <p class="lead mt-2">
        {{schedule.departure_time}} -> {{schedule.arrival_time}}
      </p>
      <p class="mt-2">
        Window Seat Price:
        <b>₹ {{ schedule.window_seat_price }}</b>
      </p>
      <p>Normal Seat Price: <b>₹ {{ schedule.normal_seat_price }}</b></p>
      <input
        type="hidden"
        id="window_seat_price"
        value="{{ schedule.window_seat_price }}"
      />
      <input
        type="hidden"
        id="normal_seat_price"
        value="{{ schedule.normal_seat_price }}"
      />
      <p class="mt-2">Total Price: <b>₹&nbsp;</b><b id="total_price">0</b></p>
      <button
        type="submit"
        form="seats"
        id="book-btn"
        class="btn btn-outline-danger btn-block mt-4"
        onclick="validateBooking()"
      >
        Book
      </button>
      <img class="buss" src="../static/img/buss.jpg" alt="bus" />
    </div>

    <script type="text/javascript">
      function calculate_price() {
        var window_seat_price =
          document.getElementById("window_seat_price").value;
        var normal_seat_price =
          document.getElementById("normal_seat_price").value;
        var window_seat_count = document.querySelectorAll(
          ".window_seat:checked"
        ).length;
        var normal_seat_count = document.querySelectorAll(
          ".normal_seat:checked"
        ).length;
        document.getElementById("total_price").innerHTML =
          window_seat_count * window_seat_price +
          normal_seat_count * normal_seat_price;
        document.getElementById("price").value =
          window_seat_count * window_seat_price +
          normal_seat_count * normal_seat_price;
      }
      function validateBooking() {
        if (document.getElementById("total_price").innerHTML == 0) {
          alert("You cannot book without selecting seats!");
          event.preventDefault();
        } else {
          document.forms[0].action = "{{ url_for('book.confirm_booking') }}";
          document.forms[0].submit();
          return true;
        }
      }

      document.getElementById("seats").addEventListener("submit", function () {
        document.getElementById("book-btn").setAttribute("disabled", "true");
      });
    </script>
  </div>
</div>

{% include 'footer.html' %} {% endblock %}

templates/seat_booking.html
{% extends 'base.html' %} {% block title %} Seat Booking {% endblock %} {%
include 'navbar.html' %} {% block content %}

<div class="container d-flex">
  <form method="post" id="seats">
    <div class="shadow flex-fill" id="bus-outline">
      {% for i in range(1, bus['seat_columns'] + 1) %}
      <div class="mb-1">
        {% if bus['seats']['window_left']['seats'][i-1]['seat_occupied'] ==
        False %}
        <!-- Left Window Seat -->
        <label title="Available" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_unoccupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="window_left_seats"
            class="seat-checkbox window_seat"
            value="{{ i }}"
            onclick="calculate_price()"
          /><span style="font-size: 11px">A{{ i }}</span></label
        >
        {% else %}
        <label title="Booked" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_occupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="window_left_seats"
            class="seat-checkbox"
            value="{{ i }}"
            disabled
          /><span style="font-size: 11px">A{{ i }}</span></label
        >
        {% endif %} {% if bus['seats']['left']['seats'][i-1]['seat_occupied'] ==
        False %}
        <!-- Left Seat -->
        <label title="Available" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_unoccupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="left_seats"
            class="seat-checkbox normal_seat"
            value="{{ i }}"
            onclick="calculate_price()"
          /><span style="font-size: 11px">B{{ i }}</span></label
        >
        {% else %}
        <label title="Booked" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_occupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="left_seats"
            class="seat-checkbox"
            value="{{ i }}"
            disabled
          /><span style="font-size: 11px">B{{ i }}</span></label
        >
        {% endif %}

        <span style="padding-left: 2rem">&nbsp;</span>

        {% if bus['seats']['right']['seats'][i-1]['seat_occupied'] == False %}
        <!-- Right Seat -->
        <label title="Available" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_unoccupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="right_seats"
            class="seat-checkbox normal_seat"
            value="{{ i }}"
            onclick="calculate_price()"
          /><span style="font-size: 11px">C{{ i }}</span></label
        >
        {% else %}
        <label title="Booked" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_occupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="right_seats"
            class="seat-checkbox"
            value="{{ i }}"
            disabled
          /><span style="font-size: 11px">C{{ i }}</span></label
        >
        {% endif %} {% if
        bus['seats']['window_right']['seats'][i-1]['seat_occupied'] == False %}
        <!-- Right Window Seat -->
        <label title="Available" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_unoccupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="window_right_seats"
            class="seat-checkbox window_seat"
            value="{{ i }}"
            onclick="calculate_price()"
          /><span style="font-size: 11px">D{{ i }}</span></label
        >
        {% else %}
        <label title="Booked" class="mx-2">
          <img
            src="{{ url_for('static', filename='img/seat_occupied.png') }}"
            height="32"
          /><br />
          <input
            type="checkbox"
            name="window_right_seats"
            class="seat-checkbox"
            value="{{ i }}"
            disabled
          /><span style="font-size: 11px">D{{ i }}</span></label
        >
        {% endif %}
      </div>
      {% endfor %}
    </div>
    <input type="hidden" name="price" id="price" />
    <input type="hidden" name="schedule_id" value="{{ bus['_id'] }}" />
    <input type="hidden" name="bus_id" value="{{ bus['bus_number'] }}" />
    <script type="text/javascript">
      function calculate_price() {
        var window_seat_price =
          document.getElementById("window_seat_price").value;
        var normal_seat_price =
          document.getElementById("normal_seat_price").value;
        var window_seat_count = document.querySelectorAll(
          ".window_seat:checked"
        ).length;
        var normal_seat_count = document.querySelectorAll(
          ".normal_seat:checked"
        ).length;
        document.getElementById("total_price").innerHTML =
          window_seat_count * window_seat_price +
          normal_seat_count * normal_seat_price;
        document.getElementById("price").value =
          window_seat_count * window_seat_price +
          normal_seat_count * normal_seat_price;
      }
      function validateBooking() {
        if (document.getElementById("total_price").innerHTML == 0) {
          alert("You cannot book without selecting seats!");
          event.preventDefault();
        } else {
          document.forms[0].action = "{{ url_for('book.confirm_booking') }}";
          document.forms[0].submit();
          return true;
        }
      }
    </script>
  </form>

  <div class="flex-fill">
    <div class="container mt-3 d-grid px-5">
      <div class="d-flex">
        <h1 class="flex-grow-1" id="bus-name"></h1>
        <h4 class="pt-2" id="bus-date">{{ book_date }}</h4>
      </div>
      <p class="lead mt-2" id="bus-startfin"></p>
      <p class="lead mt-2">{{bus.departure_time}} -> {{bus.arrival_time}}</p>
      <p class="mt-2">
        Window Seat Price:
        <b>₹ {{ bus.window_seat_price }}</b>
      </p>
      <p>Normal Seat Price: <b>₹ {{ bus.normal_seat_price }}</b></p>
      <input
        type="hidden"
        id="window_seat_price"
        value="{{ bus.window_seat_price }}"
      />
      <input
        type="hidden"
        id="normal_seat_price"
        value="{{ bus.normal_seat_price }}"
      />
      <p class="mt-2">Total Price: <b>₹&nbsp;</b><b id="total_price">0</b></p>
      <button
        type="submit"
        form="seats"
        class="btn btn-outline-danger btn-block mt-4"
        onclick="validateBooking()"
      >
        Book
      </button>
      <img class="buss" src="../static/img/buss.jpg" alt="bus" />
    </div>
    <script>
      fetch("{{url_for('bus.get_bus', bus_no=bus['bus_number'])}}")
        .then((response) => response.json())
        .then((data) => {
          document.querySelector("#bus-name").innerText = data.name;
          document.querySelector("#bus-startfin").innerText =
            data.start + " -> " + data.destination;
        });
    </script>
  </div>
</div>

{% include 'footer.html' %} 
{% endblock %}

templates/user-request-buses.html
{% extends 'base.html' %} {% block title %} Available Bus List {% endblock %} {%
include 'navbar.html' %} {% block content %}

<div class="container my-5">
  {% if buses %}
  <h1 class="text-center">Choose an available bus</h1>
  {% for bus in buses %}

 
   
      <div class="bus_list">
        <div class="bus_icon">
          <img
            class="bus_icon_image"
            src="{{ url_for('static', filename='img/buss.png') }}"
            alt="bus image here"
          />
        </div>
        <!-- <div class="bus_info_wrapper"> -->
          
          <a class="buslink" href="{{url_for('book.seat_book', schedule_id=bus._id)}}">
            <div class="bus_info">
              <div class="top_row">
                <h3 class="bus_info_name" id="bus_info_name_{{bus._id}}">
                  {{ bus.name }}
                </h3>
                <p class="bus_info_startfin" id="bus_info_startfin_{{bus._id}}">
                  {{ bus.start }} ➜ {{ bus.destination}}
                </p>
              </div>
              <div class="bottom_row">
                <p>{{ day }}</p>
                <p>{{ bus.departure_time}} -> {{bus.arrival_time}}</p>
      
                <p class="bus_info_icon">🎫Window Seat ₹{{ bus.window_seat_price}}</p>
                <p class="bus_info_icon">🎫Normal Seat ₹{{ bus.normal_seat_price}}</p>
              </div>
              <script>
                //fetch bus details from api
                fetch("{{url_for('bus.get_bus', bus_no=bus.bus_number)}}")
                  .then((res) => res.json())
                  .then((data) => {
                    document.querySelector("#bus_info_name_{{bus._id}}").textContent =
                      data.name;
                    document.querySelector(
                      "#bus_info_startfin_{{bus._id}}"
                    ).textContent = `${data.start} ➜ ${data.destination}`;
                  });
              </script>
 
          </div>
          </a>
          
       
        </div>
      
 

  {% endfor %} {% else %}
  <h1 class="text-center">No buses available</h1>
  {% endif %}
</div>


{% include 'footer.html' %} 

{% endblock %}